apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tetris
  name: tetris
spec:
  replicas: 10 
  selector:
    matchLabels:
      app: tetris
  template:
    metadata:
      labels:
        app: tetris
    spec:
      containers:
      - image: 192.168.1.10:8443/tetris-img
        name: tetris
